# Generated by Django 6.0.1 on 2026-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
