# Generated by Django 6.0.1 on 2026-01-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigade', '0002_alter_brigade_rating'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='brigade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brigade.brigade'),
            preserve_default=False,
        ),
    ]
