# Generated by Django 6.0.1 on 2026-01-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigade', '0002_alter_brigade_rating'),
        ('services', '0002_service_brigade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='brigade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brigade.brigade'),
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service')),
            ],
        ),
    ]
