# Generated by Django 6.0.1 on 2026-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('mentor', 'mentor')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
