# Generated by Django 6.0.1 on 2026-01-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('mentor', 'mentor')], default='student', max_length=100),
        ),
    ]
